name: API Testing

on:
  workflow_dispatch:
    inputs:
      Base_URL:
        required: true
        type: string
        description: Site's domain (local by default)
        default: http://localhost:5000

jobs:
  APITests:
    name: Run API Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 23
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '23'

      - name: Run API Tests
        run: |
          mvn test -Dtest=APIFunctionality.* -Dbase.url=${{ github.event.inputs.Base_URL }} -Dsurefire.failIfNoSpecifiedTests=false
