name: Smoke Testing , Allure & Lighthouse Reports

on:
  workflow_dispatch:
    inputs:
      grid_url:
        required: true
        type: string
        description: Grid to run tests on (local by default)
        default: http://localhost:4444

      base_url:
        required: true
        type: string
        description: Site's domain (local by default)
        default: http://localhost:5000

jobs:
  SmokeTests:
    name: Run Smoke Tests with Allure and Lighthouse Reports
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 23
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '23'

      - name: Launch standalone grid - Chrome
        run: |
          docker run --name grid_container -d -p 4444:4444 --shm-size=2gb selenium/standalone-chrome:latest

      - name: Run Smoke Tests
        run: |
          export GRID_URL=${{ github.event.inputs.grid_url }}
          export BASE_URL=${{ github.event.inputs.base_url }}
          echo "Running smoke tests with base URL: $BASE_URL"

          mvn -q test -Dbase_url=$BASE_URL -Dtest=WekanBoardsTests#creatingBoardTest
          mvn -q test -Dbase_url=$BASE_URL -Dtest=WekanCardsTests#addingCardToListTest
          mvn -q test -Dbase_url=$BASE_URL -Dtest=WekanCardsTests#testCardMove
          mvn -q test -Dbase_url=$BASE_URL -Dtest=WekanCardsTests#moveCardToAnotherList
          mvn -q test -Dbase_url=$BASE_URL -Dtest=WekanListsTests#moveListTest
          mvn -q test -Dbase_url=$BASE_URL -Dtest=WekanListsTests#deletingListTest
          mvn -q test -Dbase_url=$BASE_URL -Dtest=WekanListsTests#creatingListTest

      - name: Generate Allure Report
        run: |
          mvn allure:report

      - name: Upload Allure Report
        uses: actions/upload-artifact@v3
        with:
          name: allure-report
          path: target/site/allure-maven/index.html

      - name: Install Lighthouse
        run: npm install -g lighthouse

      - name: Run Lighthouse Report
        run: lighthouse ${{ github.event.inputs.base_url }} --output html --output-path ./lighthouse-report.html

      - name: Upload Lighthouse Report
        uses: actions/upload-artifact@v3
        with:
          name: lighthouse-report
          path: lighthouse-report.html

      - name: Tear Down Selenium Grid
        if: always()
        run: |
          docker stop grid_container || true
          docker rm -f grid_container || true
