name: Smoke Testing

on:
  workflow_dispatch:
    inputs:
      grid_url:
        required: true
        type: string
        description: Grid to run tests on (local by default)
        default: http://localhost:4444

      base_url:
        required: true
        type: string
        description: Site's domain (local by default)
        default: http://localhost:5000

jobs:
  SmokeTests:
    name: Smoke Test on Chrome
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 23
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '23'

      - name: Launch Selenium Grid - Chrome
        if: ${{ contains(github.event.inputs.grid_url, 'localhost') }}
        run: |
          docker run --name grid_container -d -p 4444:4444 --shm-size=2gb selenium/standalone-chrome:131.0-chromedriver-131.0-grid-4.27.0-20250101

      - name: Run Smoke Tests
        run: |
          export GRID_URL=${{ github.event.inputs.grid_url }}
          export BASE_URL=${{ github.event.inputs.base_url }}
          echo "Running smoke tests with base URL: $BASE_URL"
          mvn -q test -Dbase_url=$BASE_URL -Dtest=WekanBoardsTests#creatingBoardTest
          mvn -q test -Dbase_url=$BASE_URL -Dtest=WekanCardsTests#addingCardToListTest
          mvn -q test -Dbase_url=$BASE_URL -Dtest=WekanCardsTests#testCardMove
          mvn -q test -Dbase_url=$BASE_URL -Dtest=WekanCardsTests#moveCardToAnotherList
          mvn -q test -Dbase_url=$BASE_URL -Dtest=WekanListsTests#moveListTest
          mvn -q test -Dbase_url=$BASE_URL -Dtest=WekanListsTests#deletingListTest
          mvn -q test -Dbase_url=$BASE_URL -Dtest=WekanListsTests#creatingListTest

      - name: Tear down Selenium Grid
        if: always()
        run: |
          docker stop grid_container || true
          docker rm -f grid_container || true
