name: Smoke Testing

on:
  workflow_dispatch:
    inputs:
      grid_url:
        required: true
        type: string
        description: Grid to run tests on (local by default)
        default: http://localhost:4444

      base_url:
        required: true
        type: string
        description: Site's domain (local by default)
        default: http://localhost:5000

      chrome_131_0:
        description: 'Chrome (131.0)'
        required: false
        type: boolean
        default: true

jobs:
  TestChrome_131_0:
    name: Smoke Test Chrome 131.0
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 23
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '23'

      - name: Launch standalone grid - Chrome
        if: ${{ contains(github.event.inputs.grid_url, 'localhost') }}
        run: |
          docker run --name grid_container -d -p 4444:4444 --shm-size=2gb selenium/standalone-chrome:131.0-chromedriver-131.0-grid-4.27.0-20250101

      - name: Run Tests for PC
        if: ${{ github.event.inputs.pc_device == 'true' }}
        run: |
          export BROWSER=chrome
          export GRID_URL=${{ github.event.inputs.grid_url }}
          export BASE_URL=${{ github.event.inputs.base_url }}
          DEVICE_TYPE="pc"
          echo "Running tests for PC with base URL: $BASE_URL"
          mvn -q test -Dbase_url=$BASE_URL -Ddevice.type=$DEVICE_TYPE -Dtest=WekanBoardsTests#creatingBoardTest

          mvn -q test -Dbase_url=$BASE_URL -Ddevice.type=$DEVICE_TYPE -Dtest=WekanCardsTests#addingCardToListTest
          mvn -q test -Dbase_url=$BASE_URL -Ddevice.type=$DEVICE_TYPE -Dtest=WekanCardsTests#testCardMove
          mvn -q test -Dbase_url=$BASE_URL -Ddevice.type=$DEVICE_TYPE -Dtest=WekanCardsTests#moveCardToAnotherList


          mvn -q test -Dbase_url=$BASE_URL -Ddevice.type=$DEVICE_TYPE -Dtest=WekanListsTests#moveListTest
          mvn -q test -Dbase_url=$BASE_URL -Ddevice.type=$DEVICE_TYPE -Dtest=WekanListsTests#deletingListTest
          mvn -q test -Dbase_url=$BASE_URL -Ddevice.type=$DEVICE_TYPE -Dtest=WekanListsTests#creatingListTest
          
          # Tear down grid if exists
          docker stop grid_container || true

