name: UI Testing

on:
  workflow_dispatch:
    inputs:
      grid_url:
        required: true
        type: string
        description: Grid to run tests on (local by default)
        default: http://localhost:4444

      base_url:
        required: true
        type: string
        description: Site's domain (local by default)
        default: http://localhost:5000

      chrome_131_0:
        description: 'Chrome (131.0)'
        required: false
        type: boolean
        default: true

      firefox_133_0:
        description: 'Firefox (133.0)'
        required: false
        type: boolean
        default: false

      pc_device:
        description: 'Run responsiveness test for PC'
        required: false
        type: boolean
        default: true

      tablet_device:
        description: 'Run responsiveness test for Tablet'
        required: false
        type: boolean
        default: false

      phone_device:
        description: 'Run responsiveness test for Phone'
        required: false
        type: boolean
        default: false

jobs:
  TestChrome_131_0:
    name: Test Chrome 131.0
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.chrome_131_0 == 'true' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 23
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '23'

      - name: Launch standalone grid - Chrome
        if: ${{ contains(github.event.inputs.grid_url, 'localhost') }}
        run: |
          docker run --name grid_container -d -p 4444:4444 --shm-size=2gb selenium/standalone-chrome:131.0-chromedriver-131.0-grid-4.27.0-20250101

      - name: Run Tests for PC
        if: ${{ github.event.inputs.pc_device == 'true' }}
        run: |
          export BROWSER=chrome
          export GRID_URL=${{ github.event.inputs.grid_url }}
          export BASE_URL=${{ github.event.inputs.base_url }}
          DEVICE_TYPE="pc"
          echo "Running tests for PC with base URL: $BASE_URL"
          mvn -q test -Dbase_url=$BASE_URL -Ddevice.type=$DEVICE_TYPE -Dtest=WekanBoardsTests
          mvn -q test -Dbase_url=$BASE_URL -Ddevice.type=$DEVICE_TYPE -Dtest=WekanCardsTests
          mvn -q test -Dbase_url=$BASE_URL -Ddevice.type=$DEVICE_TYPE -Dtest=WekanListsTests

      - name: Run Tests for Tablet
        if: ${{ github.event.inputs.tablet_device == 'true' }}
        run: |
          export BROWSER=chrome
          export GRID_URL=${{ github.event.inputs.grid_url }}
          export BASE_URL=${{ github.event.inputs.base_url }}
          DEVICE_TYPE="tablet"
          echo "Running tests for Tablet with base URL: $BASE_URL"
          mvn -q test -Dbase_url=$BASE_URL -Ddevice.type=$DEVICE_TYPE -Dtest=WekanBoardsTests
          mvn -q test -Dbase_url=$BASE_URL -Ddevice.type=$DEVICE_TYPE -Dtest=WekanCardsTests
          mvn -q test -Dbase_url=$BASE_URL -Ddevice.type=$DEVICE_TYPE -Dtest=WekanListsTests

      - name: Run Tests for Phone
        if: ${{ github.event.inputs.phone_device == 'true' }}
        run: |
          export BROWSER=chrome
          export GRID_URL=${{ github.event.inputs.grid_url }}
          export BASE_URL=${{ github.event.inputs.base_url }}
          DEVICE_TYPE="phone"
          echo "Running tests for Phone with base URL: $BASE_URL"
          mvn -q test -Dbase_url=$BASE_URL -Ddevice.type=$DEVICE_TYPE -Dtest=WekanBoardsTests
          mvn -q test -Dbase_url=$BASE_URL -Ddevice.type=$DEVICE_TYPE -Dtest=WekanCardsTests
          mvn -q test -Dbase_url=$BASE_URL -Ddevice.type=$DEVICE_TYPE -Dtest=WekanListsTests
          
          # Tear down grid if exists
          docker stop grid_container || true

  TestFirefox_133_0:
    name: Test Firefox 133.0
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.firefox_133_0 == 'true' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 23
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '23'

      - name: Launch standalone grid - Firefox
        if: ${{ contains(github.event.inputs.grid_url, 'localhost') }}
        run: |
          docker run --name grid_container -d -p 4444:4444 --shm-size=2gb selenium/standalone-firefox:133.0-geckodriver-0.35-grid-4.27.0-20250101

      - name: Run Tests for PC
        if: ${{ github.event.inputs.pc_device == 'true' }}
        run: |
          export BROWSER=firefox
          export GRID_URL=${{ github.event.inputs.grid_url }}
          export BASE_URL=${{ github.event.inputs.base_url }}
          DEVICE_TYPE="pc"
          echo "Running tests for PC with base URL: $BASE_URL"
          mvn -q test -Dbase_url=$BASE_URL -Ddevice.type=$DEVICE_TYPE -Dtest=WekanBoardsTests
          mvn -q test -Dbase_url=$BASE_URL -Ddevice.type=$DEVICE_TYPE -Dtest=WekanCardsTests
          mvn -q test -Dbase_url=$BASE_URL -Ddevice.type=$DEVICE_TYPE -Dtest=WekanListsTests

      - name: Run Tests for Tablet
        if: ${{ github.event.inputs.tablet_device == 'true' }}
        run: |
          export BROWSER=firefox
          export GRID_URL=${{ github.event.inputs.grid_url }}
          export BASE_URL=${{ github.event.inputs.base_url }}
          DEVICE_TYPE="tablet"
          echo "Running tests for Tablet with base URL: $BASE_URL"
          mvn -q test -Dbase_url=$BASE_URL -Ddevice.type=$DEVICE_TYPE -Dtest=WekanBoardsTests
          mvn -q test -Dbase_url=$BASE_URL -Ddevice.type=$DEVICE_TYPE -Dtest=WekanCardsTests
          mvn -q test -Dbase_url=$BASE_URL -Ddevice.type=$DEVICE_TYPE -Dtest=WekanListsTests

      - name: Run Tests for Phone
        if: ${{ github.event.inputs.phone_device == 'true' }}
        run: |
          export BROWSER=firefox
          export GRID_URL=${{ github.event.inputs.grid_url }}
          export BASE_URL=${{ github.event.inputs.base_url }}
          DEVICE_TYPE="phone"
          echo "Running tests for Phone with base URL: $BASE_URL"
          mvn -q test -Dbase_url=$BASE_URL -Ddevice.type=$DEVICE_TYPE -Dtest=WekanBoardsTests
          mvn -q test -Dbase_url=$BASE_URL -Ddevice.type=$DEVICE_TYPE -Dtest=WekanCardsTests
          mvn -q test -Dbase_url=$BASE_URL -Ddevice.type=$DEVICE_TYPE -Dtest=WekanListsTests
          
          # Tear down grid if exists
          docker stop grid_container || true
